services:
  liquidsoap:
    build: .
    container_name: liquidsoap-radio
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - ./storage:/app/storage:ro
    environment:
      - ICECAST_HOST=192.168.1.12
      - ICECAST_PORT=8000
      - ICECAST_PASSWORD=supersecret
      - ICECAST_MOUNT=/stream
      - STATION_NAME=RadioStation
      - STATION_DESCRIPTION=RadioStation
      - STATION_GENRE=Various
      - STATION_URL=http://radio.example.com
