services:
  icecast:
    container_name: icecast
    image: ghcr.io/libretime/icecast:2.4.4
    ports:
      - "8000:8000"
    environment:
      - ICECAST_SOURCE_PASSWORD=source_password_123
      - ICECAST_ADMIN_PASSWORD=admin_password_123
      - ICECAST_ADMIN_USERNAME=admin
      - ICECAST_HOSTNAME=localhost

  liquidsoap:
    build: .
    container_name: liquidsoap
    depends_on:
      - icecast
    ports:
      - "1234:1234"
    volumes:
      - ./storage:/app/storage:ro
    environment:
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_PASSWORD=source_password_123
      - ICECAST_MOUNT=/stream
      - STATION_NAME=RadioStation
      - STATION_DESCRIPTION=RadioStation
      - STATION_GENRE=Various
      - STATION_URL=http://radio.example.com
